apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
        - setWeight: 40
        - pause: { duration: 1m }
        - setWeight: 100
