apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-qa
  namespace: argocd
spec:
  project: product-service
  source:
    repoURL: https://github.com/joneconsulting/product-service-manifests.git
    targetRevision: main
    path: overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: product-service-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
